### ISSUE TITLE
Retries every page a number of times before being able to load it

### ISSUE THREAD

**Issue by erasels** [Kinematics/NetTally#4]
![image](https://user-images.githubusercontent.com/20698806/28501870-8c582418-6fe5-11e7-8f32-ece7f1993e63.png)
The image shows the issue. Before I switched from Version 1.5.x to this version (1.9.9), I did not have this problem. The only file I migrated was user.config

Edit: Happens on all three of the XenForo websites (QQ, SB, SV) and I'm running it on Win7 with .Net 4.6 installed.

**Comment by Kinematics** [comment]
It successfully loads each page on the third attempt.  The image doesn't show the initial load attempts.

Do you use a proxy server? I know there were some issues with proxies a few months ago.  Since it's affecting multiple sites the same way, it might also be a local networking issue.  Have you tried resetting your router?

Have you tried running the older 1.5 version and seeing if the issue goes away?  If it does, would you mind checking various versions in between, to find out which version this problem first appears on?

**Comment by erasels** [comment]
Nope, not using a proxy server and my router has been reset, no difference.

Tested with the following versions:
1.5.5:                         Loads extremely fast without retrying once.
1.75:                          Same performance as 1.5.5
1.7.10:                       Loads somewhat slower than the previous versions but doesn't retry either.
1.8.0 & 1.8.1:             Both versions load very slowly and need to retry a bunch.
1.9.9:                          No change.

**Comment by Kinematics** [comment]
Are you on Vista or Windows 7?

Check the version 1.9.10a on [Google Drive](https://drive.google.com/folderview?id=0B0A0wGYYRRdaUDhYekJUZGY2dVE&usp=sharing)

There was some work I did regarding slow page loads just before 1.8.0.  It looks like you might be hitting that.  The above test build disables part of it.

**Comment by erasels** [comment]
Windows 7, yes.
Tried version 1.9.10a it certainly loads as fast as 1.5.5 but it doesn't display the Tally at the end, not sure if that's intended.

**Comment by Kinematics** [comment]
Sorry, I was in the middle of rewriting some stuff, and apparently broke something in that build.

1.9.10b should work properly.

I'll add an option to fix that setting in the full release.

**Comment by erasels** [comment]
Works like a charm now, thanks for the help!
